spring:
  application:
    name: back
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:Todolist;
    username: sa
    password:
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true